name: update-and-publish

on:
  schedule:
  # run every 12 hours
  - cron: '0 */12 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      uses: docker://ngmiller/bips-dev:latest

    - name: commit and push
      uses: EndBug/add-and-commit@v7.2.0
      if: ${{ !env.ACT }}
      with:
        default_author: github_actions
        branch: master
        message: 'cron: update bips submodule and build'
        push: true
